main_app/urls.py
from django.urls import path
from . import views
from .views import stripe_webhook
from .views import register_view, login_view, logout_view, member_area, edit_profile, packs_view, subscribe_view, apply_coupon
urlpatterns = [
    path('home/', views.index, name='index'),
    path('register/', register_view, name='register'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('member-area/', member_area, name='member_area'),
    path('edit-profile/', edit_profile, name='edit_profile'),
    path('subscribe/', views.subscribe_view, name='subscribe'),
    path('stripe/webhook/', views.stripe_webhook, name='stripe_webhook'), 
    path('packs/', packs_view, name='packs'),
    path('cancel-subscription/', views.cancel_subscription, name='cancel_subscription'),
    path('manage-packs/', views.manage_packs, name='manage_packs'),
    path('manage-packs/', views.manage_packs, name='manage_packs'),
    path('manage-packs/edit/<int:pack_id>/', views.edit_pack, name='edit_pack'),
    path('manage-packs/delete/<int:pack_id>/', views.delete_pack, name='delete_pack'),
    path('', views.splash_view, name='splash'),    
    path('manage-subscriptions/', views.manage_subscriptions, name='manage_subscriptions'),
    path('apply-coupon/<str:coupon_code>/', apply_coupon, name='apply_coupon'),
    path('send-coupon/', views.send_coupon_view, name='send_coupon'),

]

pack_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),  # Inclusion des URLs de l'application principale
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_app/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
import uuid
from django.contrib.auth import get_user_model

class CustomUser(AbstractUser):
    email = models.EmailField(unique=True)
    phone = models.CharField(max_length=15, blank=True, null=True)
    street = models.CharField(max_length=255, blank=True, null=True)
    city = models.CharField(max_length=100, blank=True, null=True)
    country = models.CharField(max_length=100, blank=True, null=True)
    avatar = models.ImageField(upload_to='avatars/', null=True, blank=True)
    is_subscribed = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)
    stripe_customer_id = models.CharField(max_length=255, blank=True, null=True)
    subscription_end_date = models.DateTimeField(null=True, blank=True)
    coupons = models.ManyToManyField('Coupon', blank=True, related_name='users')

    
    # Champ pour stocker le code promo actuel et sa date d'expiration
    current_coupon = models.ForeignKey('Coupon', on_delete=models.SET_NULL, null=True, blank=True)

    groups = models.ManyToManyField(
        'auth.Group',
        related_name='custom_user_groups',
        blank=True
    )
    user_permissions = models.ManyToManyField(
        'auth.Permission',
        related_name='custom_user_permissions',
        blank=True
    )

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return self.email
    
class Payment(models.Model):
    user = models.ForeignKey('main_app.CustomUser', on_delete=models.CASCADE)  # Utilisez une chaîne pour référencer le modèle CustomUser
    date = models.DateTimeField(auto_now_add=True)
    amount = models.DecimalField(max_digits=6, decimal_places=2)

    def __str__(self):
        return f"Paiement de {self.user.email} - {self.amount} €"

class Pack(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='pack_images/')
    download_url = models.URLField(max_length=200, blank=True, null=True)

    def __str__(self):
        return self.name

class Coupon(models.Model):
    code = models.CharField(max_length=20, unique=True)
    discount_percent = models.DecimalField(max_digits=5, decimal_places=2)
    valid_from = models.DateTimeField()
    valid_until = models.DateTimeField()
    is_active = models.BooleanField(default=True)
    is_used = models.BooleanField(default=False)  # Nouveau champ pour marquer le coupon comme utilisé
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='user_coupons')

    def __str__(self):
        return f"Coupon {self.code} - {self.discount_percent}%"


# Supprimer le modèle PromoCode si vous n'en avez plus besoin

main_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser
from .models import Pack
from .models import Coupon
from django.forms.widgets import DateTimeInput

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'password1', 'password2']


class PackForm(forms.ModelForm):
    class Meta:
        model = Pack
        fields = ['name', 'description', 'image', 'download_url']

class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'password1', 'password2']

class CustomUserChangeForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['first_name', 'last_name', 'email', 'phone', 'street', 'city', 'country', 'avatar']

class CouponForm(forms.ModelForm):
    class Meta:
        model = Coupon
        fields = ['code', 'discount_percent', 'valid_from', 'valid_until', 'is_active', 'user']
        widgets = {
            'valid_from': DateTimeInput(attrs={'type': 'datetime-local'}),
            'valid_until': DateTimeInput(attrs={'type': 'datetime-local'}),
        }

main_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .models import CustomUser, Pack, Payment
from django.contrib import messages
import stripe
from .forms import CustomUserCreationForm, RegistrationForm, CustomUserChangeForm, PackForm
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.conf import settings
from django.contrib.auth.forms import AuthenticationForm
import logging
import datetime
from django.utils import timezone
from django.contrib.admin.views.decorators import staff_member_required
from django.core.mail import send_mail
from django.utils.crypto import get_random_string
from .forms import CouponForm
from .models import Coupon
from django.views.decorators.http import require_POST
from django.http import JsonResponse




stripe.api_key = settings.STRIPE_SECRET_KEY
logger = logging.getLogger('main_app')

def can_access_packs(user):
    if user.is_subscribed:
        return True
    elif user.subscription_end_date and user.subscription_end_date > timezone.now():
        return True
    return False

@csrf_exempt
def stripe_webhook(request):
    payload = request.body
    sig_header = request.META.get('HTTP_STRIPE_SIGNATURE')
    endpoint_secret = settings.STRIPE_WEBHOOK_SECRET

    try:
        event = stripe.Webhook.construct_event(
            payload, sig_header, endpoint_secret
        )
        logger.info(f"Received Stripe event: {event['type']}")
    except (ValueError, stripe.error.SignatureVerificationError) as e:
        logger.error(f"Error processing webhook: {str(e)}")
        return HttpResponse(status=400)

    if event['type'] == 'customer.subscription.deleted':
        subscription = event['data']['object']
        customer_id = subscription.get('customer')
        logger.info(f"Subscription deleted for customer: {customer_id}")

        try:
            user = CustomUser.objects.get(stripe_customer_id=customer_id)
            user.is_subscribed = False
            
            # Mettre à jour la date de fin de l'abonnement
            current_period_end = subscription.get('current_period_end')
            if current_period_end:
                user.subscription_end_date = datetime.datetime.fromtimestamp(current_period_end)
                logger.info(f"Set subscription_end_date to {user.subscription_end_date} for user {user.email}")
            
            user.save()
        except CustomUser.DoesNotExist:
            logger.error(f"No user found with customer ID: {customer_id}")
            return HttpResponse(status=404)
        except Exception as e:
            logger.error(f"Error updating user subscription: {str(e)}")

    elif event['type'] == 'invoice.payment_succeeded':
        invoice = event['data']['object']
        customer_id = invoice.get('customer')
        logger.info(f"Invoice payment succeeded for customer: {customer_id}")

        try:
            user = CustomUser.objects.get(stripe_customer_id=customer_id)
            
            # Récupérer l'abonnement et définir la date de fin de période
            subscription_id = invoice.get('subscription')
            if subscription_id:
                subscription = stripe.Subscription.retrieve(subscription_id)
                current_period_end = subscription['current_period_end']
                
                # Mettre à jour l'état et la date de fin d'abonnement
                user.is_subscribed = True
                user.subscription_end_date = datetime.datetime.fromtimestamp(current_period_end)
                logger.info(f"User {user.email} subscription end date set to {user.subscription_end_date}")
            
            user.save()
            logger.info(f"User {user.email} subscription status updated to True")
        except CustomUser.DoesNotExist:
            logger.error(f"No user found with customer ID: {customer_id}")
            return HttpResponse(status=404)
        except Exception as e:
            logger.error(f"Error updating user subscription: {str(e)}")

    return HttpResponse(status=200)



@login_required
def cancel_subscription(request):
    user = request.user

    if not user.stripe_customer_id:
        messages.error(request, "Aucun abonnement actif à annuler.")
        return redirect('member_area')

    try:
        subscriptions = stripe.Subscription.list(customer=user.stripe_customer_id, status='active', limit=1)
        if subscriptions and len(subscriptions['data']) > 0:
            subscription_id = subscriptions['data'][0].id
            logger.info(f"Attempting to cancel subscription with ID: {subscription_id} for user {user.email}")

            # Annuler l'abonnement à la fin de la période de facturation actuelle
            stripe.Subscription.modify(
                subscription_id,
                cancel_at_period_end=True
            )

            # Mettre à jour l'utilisateur localement, mais conserver l'accès jusqu'à la fin de la période
            user.is_subscribed = True  # L'utilisateur reste abonné jusqu'à la fin de la période
            user.subscription_end_date = datetime.datetime.fromtimestamp(subscriptions['data'][0]['current_period_end'])
            user.save()
            logger.info(f"Subscription with ID: {subscription_id} set to cancel at period end for user {user.email}")

            messages.success(request, "Votre abonnement a été annulé. Vous aurez accès jusqu'à la fin de la période actuelle.")
        else:
            messages.error(request, "Aucun abonnement actif à annuler.")
    except Exception as e:
        logger.error(f"Error canceling subscription for user {user.email}: {str(e)}")
        messages.error(request, f"Une erreur s'est produite lors de l'annulation de l'abonnement : {str(e)}")
    
    return redirect('member_area')



@login_required
def create_stripe_session(request):
    user = request.user

    # Créer un client Stripe si nécessaire
    if not user.stripe_customer_id:
        customer = stripe.Customer.create(
            email=user.email,
            name=f"{user.first_name} {user.last_name}",
            phone=user.phone,
        )
        user.stripe_customer_id = customer['id']
        user.save()

    # Vérifier si l'utilisateur a un coupon valide et non utilisé
    coupon = user.user_coupons.filter(is_active=True, is_used=False, valid_until__gte=timezone.now()).first()
    discounts = []

    if coupon:
        try:
            # Créer un coupon Stripe lié au coupon de l'utilisateur
            stripe_coupon = stripe.Coupon.create(
                percent_off=coupon.discount_percent,
                duration='once'  # Le coupon ne s'applique qu'une seule fois
            )
            discounts = [{'coupon': stripe_coupon.id}]
            
            # Marquer le coupon comme utilisé après avoir vérifié que la session a été créée avec succès
        except Exception as e:
            logger.error(f"Erreur lors de la création du coupon Stripe : {str(e)}")

    # Créer la session de paiement Stripe avec le coupon si applicable
    checkout_session = stripe.checkout.Session.create(
        customer=user.stripe_customer_id,
        payment_method_types=['card'],
        line_items=[{
            'price_data': {
                'currency': 'eur',
                'product_data': {
                    'name': 'Abonnement mensuel',
                },
                'unit_amount': 1000,  # Prix de l'abonnement en centimes
            },
            'quantity': 1,
        }],
        mode='subscription',
        discounts=discounts,  # Appliquer le coupon s'il existe
        success_url=request.build_absolute_uri('/packs/'),
        cancel_url=request.build_absolute_uri('/packs/'),
    )

    # Une fois la session Stripe créée avec succès, marquer le coupon comme utilisé
    if coupon:
        coupon.is_used = True
        coupon.save()

    return redirect(checkout_session.url, code=303)




def index(request):
    packs = Pack.objects.all()
    return render(request, 'main_app/index.html', {'packs': packs})

def login_view(request):
    if request.user.is_authenticated:
        return redirect('index')  
    
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, "Connexion réussie. Bienvenue !")
                return redirect('index')
            else:
                messages.error(request, "Erreur d'authentification. Veuillez réessayer.")
        else:
            messages.error(request, "Formulaire invalide. Vérifiez vos informations.")
    else:
        form = AuthenticationForm()
    return render(request, 'main_app/login.html', {'form': form})

@login_required
def member_area(request):
    user = request.user
    coupons = user.user_coupons.filter(is_active=True, is_used=False, valid_until__gte=timezone.now())
    return render(request, 'main_app/member_area.html', {'user': user, 'coupons': coupons})

@login_required
def edit_profile(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('member_area')
    else:
        form = CustomUserChangeForm(instance=request.user)
    
    return render(request, 'main_app/edit_profile.html', {'form': form})

def logout_view(request):
    logout(request)
    return redirect('index')

def register_view(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()

main_app/templates/main_app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}CryBaby{% endblock %}</title>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'main_app/css/styles.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/hover.css/2.3.1/css/hover-min.css">
    <!-- SweetAlert2 CSS -->
    <link href="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css" rel="stylesheet">
</head>
<body style="font-family: 'Montserrat', sans-serif;">

    <!-- Progress Bar -->
    <div id="progress-bar"></div>
    
    <header class="bg-dark text-white py-3 text-center">
        <div class="container">
            <h1 class="mb-0" style="color: rgb(255, 0, 170); font-family: 'GlowingZone', sans-serif;">CryBaby</h1>
            <nav class="navbar navbar-expand-lg navbar-light mt-3 justify-content-center">
                <button class="navbar-toggler custom-toggler hvr-bounce-to-right" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-center" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link text-white" href="{% url 'index' %}">Accueil</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" href="{% url 'packs' %}">Packs</a>
                        </li>
                        {% if user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link text-white" href="{% url 'member_area' %}">Espace Membre</a>
                            </li>
                            {% if user.is_staff %}
                            <li class="nav-item">
                                <a class="nav-link text-white" href="{% url 'manage_packs' %}">Gestion des Packs</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" href="{% url 'manage_subscriptions' %}">Gestion des Abonnements</a>
                            </li>
                            {% endif %}
                            <li class="nav-item">
                                <a class="nav-link text-white" href="{% url 'logout' %}">Déconnexion</a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link text-white" href="{% url 'login' %}">Connexion</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" href="{% url 'register' %}">Inscription</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </nav>
        </div>
    </header>

    <!-- Messages Section -->
    <div class="container mt-3">
        {% if messages %}
            <div class="alert-area">
                {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                {% endfor %}
            </div>
        {% endif %}
    </div>

    <main class="container my-5">
        {% block content %}
        {% endblock %}
    </main>

    <footer class="bg-dark text-white text-center py-3">
        <p>&copy; 2024 BabyCry</p>
        <!-- Contact Information with Icons -->
        <div class="mt-3">
            <a href="https://instagram.com/yourprofile" target="_blank" class="text-white mr-3">
                <i class="fab fa-instagram footer-icon"></i> Instagram
            </a>
            <a href="mailto:your-email@example.com" class="text-white">
                <i class="fas fa-envelope footer-icon"></i> Email
            </a>
        </div>
    </footer>

    <!-- Bootstrap JS and dependencies -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <!-- SweetAlert2 JS -->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    
    <script>
        // Progress bar on scroll
        window.onscroll = function() {
            var scrollTop = document.documentElement.scrollTop;
            var scrollHeight = document.documentElement.scrollHeight - document.documentElement.clientHeight;
            var scrolled = (scrollTop / scrollHeight) * 100;
            document.getElementById("progress-bar").style.width = scrolled + "%";
        };

        // Auto-close alerts after 3 seconds
        $(document).ready(function(){
            setTimeout(function() {
                $('.alert').alert('close');
            }, 3000); // 3 seconds delay
        });
    </script>
</body>
</html>

main_app/templates/main_app/edit_pack.html
{% extends 'main_app/base.html' %}

{% block content %}
    <div class="container mt-5">
        <h2>Modifier le Pack</h2>

        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Enregistrer les modifications</button>
            <a href="{% url 'manage_packs' %}" class="btn btn-secondary">Annuler</a>
        </form>
    </div>
{% endblock %}

main_app/templates/main_app/edit_profile.html
{% extends 'main_app/base.html' %}
{% block content %}
    <h2>Modifier le profil</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Mettre à jour</button>
    </form>
{% endblock %}
vds

main_app/templates/main_app/index.html
{% extends 'main_app/base.html' %}
{% load static %}

{% block content %}
<main class="container my-5">
    <!-- Message de bienvenue -->
    <h1 class="text-center" id="welcome-message" style="font-size: 2.5rem; color: rgb(255, 0, 170); font-family: 'GlowingZone', sans-serif;">
        Bienvenue {% if user.is_authenticated %} <b>{{ user.username }}</b> {% endif %} sur CryBaby
    </h1>

    <!-- Sections -->
    <div class="sections mt-5">
        <!-- Section 1: Le concept -->
        <section id="concept" class="py-5">
            <h2 class="text-center mb-4">LE CONCEPT</h2>
            <p class="text-center">
                Ici, vous pouvez écrire un texte descriptif sur le concept de BabyCry. Utilisez cette section pour expliquer les objectifs et les caractéristiques principales de votre site.
            </p>
        </section>

        <!-- Section 2: Pluralisme Musical -->
        <section id="pluralisme-musical" class="py-5 bg-light">
            <h2 class="text-center mb-4">DIVERSITÉ MUSICALE</h2>
            <p class="text-center">
                Décrivez ici l'aspect pluraliste de BabyCry, la diversité musicale que vous proposez et comment cela enrichit l'expérience des utilisateurs.
            </p>
        </section>

        <!-- Section 3: Notre équipe -->
        <section id="notre-equipe" class="py-5">
            <h2 class="text-center mb-4">NOTRE ÉQUIPE</h2>
            <p class="text-center">
                Présentez votre équipe ici. Parlez de l'expertise, des passions et de l'engagement de ceux qui travaillent sur BabyCry.
            </p>
        </section>

        <section id="nos-conseils" class="py-5 bg-light">
            <h2 class="text-center mb-4">NOS CONSEILS</h2>
            <h3><b>RENOMMER</b> les fichiers</h3>
            <p>Renommer bien chacun des fichiers que vous avez séléctionné au fur et à mesure des semaines pour ne pas vous retrouver avec une énorme quantité de travail</p>
            <h3><b>AJOUTER</b> toujours un genre à vous</h3>
            <p>Meme si vous l'inventez tant que ça vous parle, mettre un genre c'est l'étape la plus importante de l'organisation. Toujours avec les mêmes orthographes. N'hesitez pas à créer des sous genre pour vous y retrouvez plus facilement. Un bon dossier continent MAX 150 tracks du même genre</p>
            <h3><b>VÉRIFIER</b> les BPM</h3>
            <p>BPM, BeatGrid peuvent être faux. Ne faites pas totalement confiance à la technologie !</p>
            <h3><b>INTÉGRER</b> les tracks dans vos sets</h3>
            <P>Quand vous séléctionnez un track, imaginez avec quoi il pourrait aller dans ce que vous faites deja et essayer l'enchainement le plus vite possible en live. 
            c'est le meilleur moyen de rentrer des nouveautés rapidement et reguliérement</P>
        </section>
    </div>
</main>
{% endblock %}

<!-- Include JavaScript for smooth scrolling -->
<script>
    document.addEventListener('DOMContentLoaded', function() {
        // Add smooth scrolling to all links
        document.querySelectorAll('a').forEach(anchor => {
            anchor.addEventListener('click', function(e) {
                if (this.hash !== "") {
                    e.preventDefault();
                    const hash = this.hash;
                    document.querySelector(hash).scrollIntoView({
                        behavior: 'smooth'
                    });
                }
            });
        });
    });
</script>

main_app/templates/main_app/login.html
{% extends 'main_app/base.html' %}
{% block content %}
<main class="container my-5">
    <h2 class="text-center mb-4">Connexion</h2>
    <div class="row justify-content-center">
        <div class="col-md-6">
            <form method="post" id="login-form" novalidate>
                {% csrf_token %}
                {{ form.non_field_errors }}

                <div class="form-group">
                    {{ form.username.label_tag }}
                    {{ form.username }}
                    <div class="invalid-feedback">Veuillez entrer votre nom d'utilisateur.</div>
                </div>

                <div class="form-group mt-3">
                    {{ form.password.label_tag }}
                    {{ form.password }}
                    <div class="invalid-feedback">Veuillez entrer votre mot de passe.</div>
                </div>

                <button type="submit" class="btn btn-primary btn-block mt-4">Se connecter</button>
            </form>
        </div>
    </div>
</main>
{% endblock %}

main_app/templates/main_app/manage_coupons.html
{% extends 'main_app/base.html' %}
{% block content %}
<h2>Gestion des Coupons</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Créer un Coupon</button>
</form>

<h3>Liste des Coupons</h3>
<ul>
    {% for coupon in coupons %}
        <li>{{ coupon.code }} - {{ coupon.discount_percent }}% - Expire le {{ coupon.valid_until }}</li>
    {% endfor %}
</ul>
{% endblock %}

main_app/templates/main_app/manage_packs.html
{% extends 'main_app/base.html' %}

{% block content %}
<h2 class="text-center mb-5">Gestion des Packs</h2>

<div class="row">
    <div class="col-md-8">
        <h3>Liste des packs</h3>
        <ul class="list-group">
            {% for pack in packs %}
            <li class="list-group-item d-flex justify-content-between align-items-center">
                {{ pack.name }}
                <a href="{% url 'manage_packs' %}?edit_pack_id={{ pack.id }}" class="btn btn-sm btn-secondary">Modifier</a>
            </li>
            {% endfor %}
        </ul>
    </div>

    <div class="col-md-4">
        {% if pack_to_edit %}
            <h3>Modifier le pack : {{ pack_to_edit.name }}</h3>
        {% else %}
            <h3>Ajouter un nouveau pack</h3>
        {% endif %}
        <!-- Formulaire d'ajout ou de modification -->
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn {% if pack_to_edit %}btn-primary{% else %}btn-success{% endif %}">
                {% if pack_to_edit %}Enregistrer les modifications{% else %}Ajouter le pack{% endif %}
            </button>
        </form>
    </div>
</div>

{% endblock %}

main_app/templates/main_app/send_coupon.html
{% extends 'main_app/base.html' %}

{% block content %}
<div class="container mt-5">
    <h2>Envoyer un coupon</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Envoyer le coupon</button>
    </form>
</div>
{% endblock %}

<script>
    $(document).ready(function() {
        $('#id_valid_from, #id_valid_until').datepicker({
            dateFormat: 'yy-mm-dd',
            changeMonth: true,
            changeYear: true
        });
    });
</script>

main_app/templates/main_app/subscribe.html
{% extends 'main_app/base.html' %}
{% load static %}
{% block content %}
<h1>Connexion</h1>
<form method="post" action="{% url 'login' %}">
    {% csrf_token %}
    <label for="email">Email :</label>
    <input type="email" id="email" name="email" required>
    
    <label for="password">Mot de passe :</label>
    <input type="password" id="password" name="password" required>
    
    <button type="submit">Se connecter</button>
</form>
{% endblock %}